#!/bin/bash

set -e

# cd ~/bitdust/deploy/ubuntu_devel

version=`cat ../version`
dirname="bitdust-dev-$version.orig"
packagename="bitdust-dev_${version}_all.deb"

echo "remove old files"
rm -f bitdust-dev*.deb 
rm -f bitdust-dev*.changes 
rm -f bitdust-dev*.dsc 
rm -f bitdust-dev*.gz 
rm -f bitdust-dev*.upload
rm -f bitdust-dev*.build

echo "prepare workspace folders"
rm -rf workspace
mkdir workspace
cd workspace
# mkdir src
mkdir bin
mkdir doc
mkdir pixmaps
mkdir shortcuts
mkdir autostart
mkdir apt
mkdir cron
mkdir cron/daily
mkdir cron/hourly
mkdir debian
mkdir debian/source
mkdir default
cd ..

echo "prepare debian files"
echo "3.0 (native)" > workspace/debian/source/format
cp debian/compat workspace/debian/
cp debian/control workspace/debian/
cp debian/config workspace/debian/
cp debian/templates workspace/debian/
cp debian/rules workspace/debian/
cp debian/install workspace/debian/
python -c "import sys;src=open(sys.argv[1]).read();src=src.replace('{version}',sys.argv[2]);open(sys.argv[1],'w').write(src);" workspace/debian/control $version
cp debian/changelog workspace/debian/
python -c "import sys,time;src=open(sys.argv[1]).read();src=src.replace('{version}',sys.argv[2]);src=src.replace('{date}',time.strftime('%a, %d %b %Y %H:%M:%S'));src=src.replace('{changelog}',open('../../CHANGELOG.txt').read());open(sys.argv[1],'w').write(src);" workspace/debian/changelog $version
cp debian/preinst workspace/debian
cp debian/postinst workspace/debian
cp debian/prerm workspace/debian
cp debian/copyright workspace/debian
# cp debian/bitdust.cron.daily workspace/debian 
cp debian/bitdust-dev.cron.hourly workspace/debian 
cp debian/bitdust-dev.menu workspace/shortcuts 

echo "prepare project files"
cp debian/bitdust workspace/bin
cp debian/bitdustd workspace/bin
cp debian/bitdustb workspace/bin
cp debian/bitdust-dev.1 workspace/doc
cp debian/bitdust.xpm workspace/pixmaps
cp debian/bitdust.png workspace/pixmaps
cp debian/bitdust-dev.list workspace/apt 
cp debian/bitdust.desktop workspace/shortcuts
cp -T debian/bitdust-dev-autostart.desktop workspace/autostart/bitdust-dev.desktop
cp -T debian/bitdust-dev.default workspace/default/bitdust-dev-update 

# echo "build sources"
# ../sources/0-build

# echo "copy sources"
# cp -r ../sources/workspace/bitdust/* workspace/src/

# echo "rename LICENSE.txt file"
# mv workspace/src/LICENSE.txt workspace/src/TERMS.txt

# echo "create repo.txt file"
# echo "devel" > workspace/src/repo.txt
# echo "http://bitdust.io/deb/devel" >> workspace/src/repo.txt

echo "setting permissions"
find workspace/debian -type d | xargs chmod 0755
find workspace/debian -type f | xargs chmod 0644
chmod 0755 workspace/bin/bitdust
chmod 0755 workspace/bin/bitdustb
chmod 0755 workspace/bin/bitdustd
chmod 0755 workspace/debian/rules
chmod 0755 workspace/debian/postinst
chmod 0755 workspace/debian/preinst
chmod 0755 workspace/debian/prerm
chmod 0755 workspace/debian/bitdust-dev.cron.hourly
# chmod 0755 workspace/debian/bitdust.cron.daily

echo "DONE!"

exit 0

