#!/bin/bash

set -e

# cd ~/bitdust/deploy/ubuntu_devel

echo "building .deb file"
cd workspace
# debuild -k12E49B66 > ../build.log
debuild -kB3A000A9 > ../build.log
cd ..

tail -13 build.log

echo "DONE!"

exit 0


