#!/bin/sh

set -e

# cd ~/bitdust/release/ubuntu_devel

version=`cat ../version`
debfile="bitdust-dev_${version}_all.deb"
changesfile="bitdust-dev_${version}_amd64.changes"

echo "copy .deb file into public location"
rm -f /var/www/download/bitdust-dev.deb
cp $debfile /var/www/download/bitdust-dev.deb

echo "doing reprepro"
reprepro -V -b /var/www/deb/devel include devel $changesfile
reprepro -V -b /var/www/deb/devel includedeb devel $debfile
reprepro -V -b /var/www/deb/devel list devel

rm -f bitdust-dev_*

echo "DONE!!! apt repo updated!"

exit 0

