exclude: |
  (?x)(
      ^bitdust_forks/|
      ^devops/|
      ^icons/|
      ^regress/|
      ^release/|
      ^scripts/|
      ^tests/|
      ^.git/|
      ^.circleci/|
      ^.github/|
      ^.__pycache__/|
      ^.hg/|
      ^.mypy_cache/|
      ^.tox/|
      ^.venv/|
      ^venv/|
      ^_build/|
      ^buck-out/|
      ^build/|
      ^dist/
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        args: ['--style=.style.yapf', '--in-place']

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.1
    hooks:
      - id: pycln
        args: [--config=bitdust-precommit.toml]
