[tool.black]
line-length = 90
exclude = '''
\.git |
\.__pycache__|
\.hg|
\.mypy_cache|
\.tox|
\.venv|
_build|
buck-out|
build|
dist
'''

[tool.pycln]
all = true

[tool.isort]
line_length = 90
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
