#
# Dockerfile
#
# Copyright (C) 2018 Stanislav Evseev, Veselin Penev  https://bitdust.io
#
# This file (Dockerfile) is part of BitDust Software.
#
# BitDust is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# BitDust Software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with BitDust Software.  If not, see <http://www.gnu.org/licenses/>.
#
# Please contact us if you have any questions at bitdust.io@gmail.com

FROM python:3.11

ENV BITDUST_LOG_USE_COLORS=0

ENV BITDUST_IN_DOCKER=1

WORKDIR /app

COPY . /app/bitdust

RUN python3 /app/bitdust/bitdust.py install

RUN echo '#!/bin/sh\n /root/.bitdust/venv/bin/python3 /app/bitdust/bitdust.py "$@"' > /bin/bitdust && chmod +x /bin/bitdust

RUN find /app/bitdust -type f -name "*.py" -exec sed -i -e 's/_Debug = False/_Debug = True/g' {} +

CMD bitdust --appdir /bitdust_host_storage set debug 14 && bitdust --appdir /bitdust_host_storage set services/identity-server/host bitdust-at-google-124315045881.europe-west1.run.app && bitdust --appdir /bitdust_host_storage set services/identity-server/enabled true && bitdust --appdir /bitdust_host_storage id server
