#!/bin/bash
#
# The script can be used to make a static snapshot of the repository files.
#
# Usage:
#
#     git clone https://github.com/bitdust-io/devel.git bitdust
#     mkdir bitdust_snapshot/
#     cp bitdust/import bitdust_snapshot/
#     cd bitdust_snapshot/
#     ./import ../bitdust/

tmppath="$1.import"
curpath=`pwd`
git pull
cd "$1"
sourcepath=`pwd`
mkdir "$tmppath"
git checkout-index -a -f --prefix="$tmppath/"
cd "$tmppath"
cp -r -v * "$curpath"
rm -rf "$tmppath"
cd "$curpath"
exit 0
