#!/bin/bash
BITDUST_DIR="~/.bitdust"
if [ -f /usr/share/bitdust/installdir ]; then
    BITDUST_DIR=`cat /usr/share/bitdust/installdir`
fi
/usr/bin/nohup /usr/bin/python $BITDUST_DIR/src/bitdust.py $@ >/dev/null 2>/dev/null &
