#!/bin/bash
BITDUST_DIR="~/.bitdust"
if [ -f /usr/share/bitdust/installdir ]; then
    BITDUST_DIR=`cat /usr/share/bitdust/installdir`
fi
cd $BITDUST_DIR/src
/usr/bin/nohup /usr/bin/python bitdust.py $@ >/dev/null 2>/dev/null &
