#!/bin/sh

set -e

. /usr/share/debconf/confmodule

INSTALLATOR=""
BITDUST_DIR="./bitdust"
if [ -f /usr/share/bitdust/user ]; then
    INSTALLATOR=`cat /usr/share/bitdust/user`
    BITDUST_DIR="/home/$INSTALLATOR/.bitdust"
fi
# echo "conf.INSTALLATOR=$INSTALLATOR"

if [ -f /usr/share/bitdust/installdir ]; then
    BITDUST_DIR=`cat /usr/share/bitdust/installdir`
fi
# echo "conf.BITDUST_DIR=$BITDUST_DIR"

db_set bitdust/installdir $BITDUST_DIR

db_input high bitdust/installdir || true
db_go

db_get bitdust/installdir
if [ "$RET" = "false" ]; then
    db_set bitdust/installdir $BITDUST_DIR
fi

if [ "$RET" = "" ]; then
    db_set bitdust/installdir $BITDUST_DIR
fi

if [ "$RET" != "" ]; then
    BITDUST_DIR=$RET
fi

# echo "RET=$RET"

# if [ "$RET" == "" ]; then
# fi

mkdir -p /usr/share/bitdust
echo "$BITDUST_DIR" > /usr/share/bitdust/installdir  

exit 0
