#!/bin/sh

set -e

if [ "$1" = remove ] ; then

    INSTALLATOR=""
    if [ -f /usr/share/bitdust/user ]; then
        INSTALLATOR=`cat /usr/share/bitdust/user`
    fi    

    BITDUST_DIR="./bitdust"
    if [ -f /usr/share/bitdust/installdir ]; then
        BITDUST_DIR=`cat /usr/share/bitdust/installdir`
    fi

    if [ -n "$INSTALLATOR" ]; then
        su $INSTALLATOR -c "bitdust stop" > /dev/null 2>&1 &
    fi

    rm -f /usr/share/bitdust/user

    rm -f /usr/share/bitdust/installdir
    
    find /usr/share/bitdust -type f -name '*.pyc' -exec rm -f {} \;
    
    if [ -n "$SUDO_USER" ]; then
        if [ -d "/home/$SUDO_USER/.config/autostart/" ] ; then
            rm -rf /home/$SUDO_USER/.config/autostart/bitdust-dev.desktop
        fi
    fi
    
    rm -f /home/$SUDO_USER/.icons/bitdust.png
    
    rm -rf $BITDUST_DIR
fi

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
    db_purge
fi

#DEBHELPER#

exit 0
