#!/usr/bin/python
#
import os
import sys
if __name__ == "__main__":
    root_dir = '/usr/share/bitpie'
    os.chdir(root_dir)
    sys.path.append(root_dir)
    import p2p.bpmain
    ret = p2p.bpmain.main()
    os._exit(ret)
