#!/bin/sh

#echo "starting bitpie.postinst"

set -e

INSTALLATOR=""
if [ -f /usr/share/bitpie/user.txt ]; then
    INSTALLATOR=`cat /usr/share/bitpie/user.txt`
fi

if [ "$1" = configure ] ; then

    APT_KEY="`which apt-key 2> /dev/null`"
    if [ -x "$APT_KEY" ]; then
        "$APT_KEY" add - >/dev/null 2>&1 <<KEYDATA
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.10 (GNU/Linux)

mI0ETyVpIQEEAMx6LmakgzSke1cUm4f0AYvXR+FtylH2gPbYQQxCgax1E9Jz/kEq
5+Kv4XZq+gYcxS6IA/PNia6mJVYARPhHAyTbF+svv6S5Jd7qztUqur9J6iP/hqsT
seIjocVciM81C3vIbr+RTmLPqDVvz5ic2y5g2I4nv68kbp1PgO2gbQErABEBAAG0
IFZlc2VsaW4gUGVuZXYgPHZlc2VsbG92QG1haWwucnU+iLgEEwECACIFAk8laSEC
GwMGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELZYOyo9a3KHMuoD/24JJVxB
8hubpNSdC03WJrbWws9jaajehIgq9R4Vo9FGLJzznqSTYCo2f80hVo8AjxjIPps3
oyNKPKkZdUecUCOriDC3/hNybw5dU9/irNZlhVskvGktUgaECe1RO/dSGSEhT9Kw
nbLGo8/ACPtI9uDdcFAY2MhmaenSMje11Xv4uI0ETyVpIQEEAMX0uRa//iTooqvk
uD905AYYa+jbqk/kcmBbnXCHM+qenXGwAkqdgv+1F7213ZQEJSi0/xnb+l2ukJf5
EocrMQQ7ahEp4bub6zKmnWdFLL5awEshA2pw6bVNhe/cU5heuuiINAommknhGwF6
axMWD7RWeOiDoMqSsWxPSo93iNKzABEBAAGInwQYAQIACQUCTyVpIQIbDAAKCRC2
WDsqPWtyh5e7BACbZ/4T1S7hud0aPR8nDnmEJGTcp907arJ/l/Z32auswpHVM7tu
kkxVWHPNBD4sOY0w3uW22poLkoUI4n96OyatvNAOhKYnEZKpPrD2X9pa7jRy2KnP
ce5z7IJVNKABDLsjFCgqH9IUYcthOCfCJ1qchDnBXybeON34Q+B0sXuQgg==
=o/7y
-----END PGP PUBLIC KEY BLOCK-----
KEYDATA
    fi    

    if [ -x "`which update-menus 2>/dev/null`" ] ; then
        update-menus
    fi

    find /usr/share/bitpie -type f -name '*.pyc' -exec rm -f {} \;

    if [ -d "/home/$INSTALLATOR/.config/autostart/" ] ; then
        mkdir -p /home/$INSTALLATOR/.config/autostart/
        cp /usr/share/bitpie/bitpie.desktop /home/$INSTALLATOR/.config/autostart/
        chown $INSTALLATOR:$INSTALLATOR /home/$INSTALLATOR/.config/autostart/bitpie.desktop
    fi    

    if [ -n "$INSTALLATOR" ]; then

        echo "restarting BitPie.NET from user $INSTALLATOR"
        nohup su $INSTALLATOR -c "/usr/bin/bitpie restart" >/dev/null &

    fi
fi

#echo "bitpie.postinst done"

#DEBHELPER#

exit 0

