#!/bin/sh

set -e

cd ~/bitdust/release/ubuntu_stable

version=`cat ../version`
debfile="bitdust-stable_${version}_all.deb"
changesfile="bitdust-stable_${version}_amd64.changes"

echo "copy .deb file into public location"
rm -f /var/www/bitdust-ubuntu-stable.deb
cp $debfile /var/www/download/bitdust-ubuntu-stable.deb

echo "doing reprepro"
reprepro -V -b /var/www/deb/stable include stable $changesfile
reprepro -V -b /var/www/deb/stable includedeb stable $debfile
reprepro -V -b /var/www/deb/stable list stable

rm -f bitdust-stable_*

echo "DONE!!! stable repo updated!"

exit 0

