#!/bin/sh

set -e

cd ~/bitpie/release/ubuntu_stable

version=`cat ../version`
debfile="bitpie_${version}_all.deb"
changesfile="bitpie_${version}_amd64.changes"

echo "copy .deb file into public location"
rm -f /var/www/bitpie-ubuntu-stable.deb
cp $debfile /var/www/download/bitpie-ubuntu-stable.deb

echo "doing reprepro"
reprepro -V -b /var/www/deb/stable include stable $changesfile
reprepro -V -b /var/www/deb/stable includedeb stable $debfile
reprepro -V -b /var/www/deb/stable list stable

rm -f bitpie_*

echo "DONE!!! stable repo updated!"

exit 0

