#!/bin/bash

cd ~/bitpie/release/sources

echo "[ prepare workspace folder ]"
rm -rf workspace
mkdir workspace
cp MANIFEST.in workspace

echo "[ export from git repo into workspace ]"
pushd ../.. >/dev/null
git archive master | (cd release/sources/workspace; tar x)
popd >/dev/null

echo "[ prepare setup.py file ]"
cp setup.py workspace
version=`cat ../version`
regexp="s/{version}/$version/g;"
perl -i -pe $regexp workspace/setup.py 

echo "[ remove some files ]"
cd workspace
rm commit.bat
rm commit.sh
rm -rf screenshots

echo "[ sources done ]"


