#!/bin/bash


echo "[ prepare workspace folder ]"
rm -rf workspace
mkdir workspace
mkdir workspace/bitdust
cp MANIFEST.in workspace

echo "[ export from git repo into workspace ]"
pushd ../.. >/dev/null
git archive master | (cd release/sources/workspace/bitdust; tar x)
popd >/dev/null

echo "[ prepare setup.py file ]"
cp setup.py workspace
version=`cat ../version`
regexp="s/{version}/$version/g;"
perl -i -pe $regexp workspace/setup.py 

echo "[ remove some files ]"
cd workspace/bitdust
rm -rfv .dockerignore
rm -rfv .editorconfig
rm -rfv .gitignore
rm -rfv .circleci
rm -rfv Dockerfile
rm -rfv history
rm -rfv Makefile
rm -rfv networks.json
rm -rfv .travis.yml
rm -rfv MANIFEST.in
rm -rfv setup.py
rm -rfv setup_gen.py
rm -rfv setup.cfg
rm -rfv commit.sh
rm -rfv devops/
rm -rfv regress/
rm -rfv tests/dht/
rm -rfv tests/experiments/
rm -rfv scripts/
rm -rf screenshots/*
rm -vrf screenshots
rm -rf release/*
rm -vrf release
rm -rf icons/*
rm -vfr icons
rm -rf fonts/*
rm -vfr fonts
rm -rf web/static/*
rm -fr web/html/*

echo "[ move some files to the top level ]"
mv -v *.txt ..
mv -v *.md ..

cd ..
cd ..
echo "[ sources done ]"
