#!/bin/sh

cd ~/bitdust/release/sources


echo '[ run "python setup.py sdist" ]'
rm -rf bitdust.tar.gz
cd workspace
rm -rf dist
python setup.py sdist >../sdist.log


echo "[ publish sources ]"
cp dist/*.tar.gz /var/www/download/bitdust.tar.gz
cp -v dist/*.tar.gz /var/www/download/
rm -rf dist
cd ..
