#
# docker-compose.yml
#
# Copyright (C) 2008 Stanislav Evseev, Veselin Penev  https://bitdust.io
#
# This file (docker-compose.yml) is part of BitDust Software.
#
# BitDust is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# BitDust Software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with BitDust Software.  If not, see <http://www.gnu.org/licenses/>.
#
# Please contact us if you have any questions at bitdust.io@gmail.com

version: "3.4"

services:



  id-a:
    image: bitdust/app
    ports:
      - "10601:22"

  id-b:
    image: bitdust/app
    ports:
      - "10602:22"

  id-c:
    image: bitdust/app
    ports:
      - "10603:22"

  id-dead:
    image: bitdust/app
    ports:
      - "10604:22"

  dht-1:
    image: bitdust/app
    ports:
      - "10611:22"

  dht-2:
    image: bitdust/app
    ports:
      - "10612:22"
    links:
      - dht-1

  stun-1:
    image: bitdust/app
    ports:
      - "10621:22"
    links:
      - dht-2

  supplier-1:
    image: bitdust/app
    ports:
      - "10641:22"
    links:
      - dht-2
      - stun-1
      - id-a
      - id-b
      - id-c
      - id-dead

  supplier-2:
    image: bitdust/app
    ports:
      - "10642:22"
    links:
      - dht-2
      - stun-1
      - id-a
      - id-b
      - id-c
      - id-dead

  customer-1:
    image: bitdust/app
    ports:
      - "10651:22"
    volumes:
      - customer_1:/customer_1
    links:
      - dht-2
      - stun-1
      - id-a
      - id-b
      - id-c
      - id-dead

  customer-2:
    image: bitdust/app
    ports:
      - "10655:22"
    volumes:
      - customer_2:/customer_2
    links:
      - dht-2
      - stun-1
      - id-a
      - id-b
      - id-c
      - id-dead

  broker-1:
    image: bitdust/app
    ports:
      - "10661:22"
    links:
      - dht-2
      - stun-1
      - id-a
      - id-b
      - id-c
      - id-dead

  broker-2:
    image: bitdust/app
    ports:
      - "10662:22"
    links:
      - dht-2
      - stun-1
      - id-a
      - id-b
      - id-c
      - id-dead

  broker-3:
    image: bitdust/app
    ports:
      - "10663:22"
    links:
      - dht-2
      - stun-1
      - id-a
      - id-b
      - id-c
      - id-dead

  broker-4:
    image: bitdust/app
    ports:
      - "10664:22"
    links:
      - dht-2
      - stun-1
      - id-a
      - id-b
      - id-c
      - id-dead

  broker-rotated:
    image: bitdust/app
    ports:
      - "10665:22"
    links:
      - dht-2
      - stun-1
      - id-a
      - id-b
      - id-c
      - id-dead



  tester:
    image: bitdust/tester
    cap_add:
      - SYS_PTRACE
    privileged: true
    stdin_open: true
    tty: true
    links:
      - id-a
      - id-b
      - id-c
      - id-dead
      - dht-1
      - dht-2
      - stun-1
      - supplier-1
      - supplier-2
      - customer-1
      - customer-2
      - broker-1
      - broker-2
      - broker-3
      - broker-4
      - broker-rotated

    volumes:
      - customer_1:/customer_1
      - customer_2:/customer_2



volumes:
  customer_1:
  customer_2:

