.TH bitdust 1 "" "" "USER COMMANDS" 
.SH NAME
BitDust \- peer-to-peer backup utility
.SH SYNOPSIS
.B bitdust
.RI [ options ] 
.SH DESCRIPTION
.PP
Imagine that you need the
.B most reliable
to keep the contents of a folder on your hard drive and be sure that 
.B only you have access
to this data.
.PP
We propose to divide the data into blocks, compress, encrypt and store them on the computers of 
.B other users.
.PP 
The system is designed in such a way that will keep track of each user which stores your information, 
and each block of your data and 
.B maintain a state
in which you can always 
.B get your data back.
.PP
This is very similar to the well-known torrents ... but on the contrary!
.SH OPTIONS
.TP
.B show
execute the programm and show the main window
.TP
.B stop
stop the programm 
.TP
.B twistedlog
show twisted log messages
.TP
.B log \<file name\>
print log to the file (by default in Gui version)
.TP
.B logs
print logs to stdout
.TP
.B msg \<idurl\> \<text\>
send a short message without Gui
.TP
.B help
show options list
.SH AUTHOR
BitDust Software was written by Vincent Cate, Derek Cate and Veselin Penev.
.PP
This manual page was written by Veselin Penev <veselin@bitdust.io>,
for the Debian project (and may be used by others).
.PP
Copyright: BitDust Inc., 2014 
