#!/bin/sh

#echo "starting bitdust.preinst"

set -e

if [ "$1" = install ] ; then
    if [ -n "$SUDO_USER" ]; then
        echo "bitdust is installed from user $SUDO_USER, remember this"
        mkdir -p /usr/share/bitdust/
        echo "$SUDO_USER" > /usr/share/bitdust/user.txt
    fi
fi

#echo "bitdust.preinst done"


#DEBHELPER#

exit 0
