#!/bin/sh

#echo "starting bitdust.prerm"

set -e

INSTALLATOR=""
if [ -f /usr/share/bitdust/user.txt ]; then
    INSTALLATOR=`cat /usr/share/bitdust/user.txt`
fi    

if [ "$1" = remove ] ; then

    if [ -n "$INSTALLATOR" ]; then
        #echo "stopping bitdust from user $INSTALLATOR"
        nohup su $INSTALLATOR -c "/usr/bin/bitdust stop" >/dev/null &
    fi

    rm -f /usr/share/bitdust/user.txt
    
    find /usr/share/bitdust -type f -name '*.pyc' -exec rm -f {} \;
    
    if [ -n "$SUDO_USER" ]; then
        if [ -d "/home/$SUDO_USER/.config/autostart/" ] ; then
            rm -rf /home/$SUDO_USER/.config/autostart/bitdust.desktop
        fi
    fi
    
    rm -f /home/$SUDO_USER/.icons/bitdust.png
fi

#echo "bitdust.prerm done"

#DEBHELPER#

exit 0

