#!/bin/sh

#echo "starting bitdust.postinst"

set -e

INSTALLATOR=""
if [ -f /usr/share/bitdust/user.txt ]; then
    INSTALLATOR=`cat /usr/share/bitdust/user.txt`
fi

if [ "$1" = configure ] ; then

    APT_KEY="`which apt-key 2> /dev/null`"
    if [ -x "$APT_KEY" ]; then
        "$APT_KEY" add - >/dev/null 2>&1 <<KEYDATA
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.11 (GNU/Linux)

mQENBFP7R3QBCADGoqpfHfOSsXeV9uXkqKz9lyMp+/Cr7ZKnCkuM4ZxBD1mi0rY6
0otsmnzCrzMCnusOA+zL1FqiH/0DoReScNrrg2sUvQIoQ4zf+SYYtFrmmMD+j5ZK
z0RKJEZea6K5c2fjdLGDYpZWNRHp8vUSA81LCLRMqJq8UZFmCev3Gf9voU/+U0lu
8l+mxG488WL4v7R3vg2Qqs4wxjtBXh8khBTZqDAJJR3EcB4BnVjUoE7dRpQxFmLl
v0PnDKxrBBvGTrv5g1Hq+/9JfrJtahUr8cFKEVrpVoW//m5VqufqjtPhjrxposBZ
IJBBSovEhuVPciJ3rQnjO6cuvMHTICGlHF8rABEBAAG0OVZlc2VsaW4gUGVuZXYg
KEJpdFBpZS5ORVQgZGV2ZWxvcGVyKSA8dmVzZWxpbkBiaXRwaWUubmV0PokBOAQT
AQIAIgUCU/tHdAIbAwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQg9PnvCko
zy4Izwf/dr5pATD75DzEw0pAiW1ap+ErurXUTduOggCtNE4xOk07mD9Y+FuRuI2t
TSI4CyjlnGvf72wGbgJA5ohBGUdiawKnmaDDRr6fWQYxtKMnOUKcEvuKfLaS887e
s+OTVXPUgQXzWIF2lyQlnT6lwslINWJrCCb/pCKwiSWlPM828YI1yJobWenzWbB+
pI1P0foende8A/V73joBDtRjZz0c6fdRbwXTs3ZzVdG+yNRjCHowrXEJwQbZHNkp
KzYj9uwFOYO9fy1mVlT59IQPYnbfq2NvZDLAiVZr1aAyTrfZ7By/XDPywkiEzxUv
Pe1YgImQCzcFBrchYDH9pTDjm1oaarkBDQRT+0d0AQgAq1PMgnsK/MLTRYHAjIU4
D1LTRoQHx43Ctx05RrTQ3riFhlJKm35uWHDDUYu2eyo2Q91nXVoJhluhHC6YH4G6
x51IDXCh6marG8XbsQEYGoRwpq1Te+rDKc0Wtu5V/kzFDhhU+yCEWHKLEiuHxjwI
kPAFd8+X0cB/T+bBNeGhBzJiAb45SbzC/gRGQrPVAzCY/DOl48clsnB9TeBoB7zW
4IhMaqmCpAfhuJ27nS59IS9Pco5srbdHL1eeuRM0VE7hUuLMdzYBXUyOPsj51a/x
GWmtUWHRz8nk8gQkpmDX4Idt6ioZb2l2cRaV2IA+8cAoq83G+/qQU9QCqv+3GK0m
sQARAQABiQEfBBgBAgAJBQJT+0d0AhsMAAoJEIPT57wpKM8uLWUH/jNbgc60Ff2V
EDZBjRfKOVyWclooGqorp/wUFvV3niHFL4PI4O4qVsVdBXxaSP7cyNz8FR2zDtg+
H/cEy/Q2SBU7jM8JRGs9NBF0ExRuaSzgwtzWMRHgyEZX/Xpxonk+dMVvMyz9p4CP
r+1Rlisw43ZUo1l6+P3sVLoHqdqGeobZWqdBw8RxxH4l7NLkbDfrHyW0ZOmWayhd
NaRQyPe3ZRJGt7yPTriThuDZCVMQrXHY7uJ1o+dBfdJOxHtyH/AA5AO8Ld01pvDD
A4ugWxAvW9Tt0sLmBj/W2pQmIyPLCm1SzDBPMlao+9+0EIwJkOr4VVUgC8DMIpuH
5Aw5PeBFMnI=
=PUmG
-----END PGP PUBLIC KEY BLOCK-----
KEYDATA
    fi    

    if [ -x "`which update-menus 2>/dev/null`" ] ; then
        update-menus
    fi

    find /usr/share/bitdust -type f -name '*.pyc' -exec rm -f {} \;

    if [ -d "/home/$INSTALLATOR/.config/autostart/" ] ; then
        mkdir -p /home/$INSTALLATOR/.config/autostart/
        cp /usr/share/bitdust/bitdust.desktop /home/$INSTALLATOR/.config/autostart/
        chown $INSTALLATOR:$INSTALLATOR /home/$INSTALLATOR/.config/autostart/bitdust.desktop
    fi    

    mkdir -p /home/$INSTALLATOR/.icons/
    cp /usr/share/icons/bitdust.png /home/$INSTALLATOR/.icons/
    
    if [ -n "$INSTALLATOR" ]; then

        echo "restarting BitDust from user $INSTALLATOR"
        nohup su $INSTALLATOR -c "/usr/bin/bitdust restart" >/dev/null &

    fi
fi

#echo "bitdust.postinst done"

#DEBHELPER#

exit 0

