#!/bin/bash

./stop
# ./reset
./up

# ./idcreate "$1"

if [ '1' == '1' ]; 
then
  # rm -rf ~/.bitpie
  # ./bd set services/supplier/enabled true
  # ./bd set services/proxy-transport/enabled false
  # ./bd set services/proxy-server/enabled false
  # ./bd set services/udp-transport/enabled true
  ./bd set tcp true
  ./bd set udp true
  # ./bd set donated 10GB
  ./bd set debug 8
  rm -rf ~/.bitdust/temp/*
  # rm -rf ~/.bitdust/logs/*
  # rm -rf ~/.bitdust/identitycache/*
  # rm -rf ~/.bitdust/customers/*
  # rm ~/.bitdust/metadata/supplierids
  # rm ~/.bitdust/metadata/customerids
  # rm ~/.bitdust/metadata/space
fi

./go

exit 0

