#!/bin/bash

# sudo apt-get update
# sudo apt-get install git nano python python-twisted python-pyasn1 python-openssl python-crypto python-pycurl
# git clone https://github.com/datahaven-net/datahaven.git ~/datahaven.git
# cd ~/datahaven.git/datahaven
# python dhn.py register "$1"
# python dhn.py set debug 18
# python dhn.py

rm -rf bitdust
git clone git@vps1000:bitdust






