#!/bin/bash

# echo "suppliers:"
# cat .bitdust/metadata/supplierids
# echo

# echo "customers:"
# cat .bitdust/metadata/customerids
# echo

# echo "space:"
# cat .bitdust/metadata/space
# echo

# echo "used:"
# cat .bitdust/metadata/spaceused
# echo

# tail -10 log

./bd backups

exit 0
