#!/bin/bash

echo "";

for srv in `python3 -c "import bitdust.userid.known_servers; s=bitdust.userid.known_servers.by_host(); print(' '.join(['{}:{}'.format(i.decode(), s[i][0]) for i in s]))"`; do
    echo "$srv";
    curl -I --connect-timeout 10 $srv 2>/dev/null | grep "HTTP";
    echo "";
done
