#!/bin/bash

echo "running 'pskill $1'"

LINES=`ps auxww | grep "$1" | grep -v grep | grep -v kill`
[ -n "$LINES" ] && echo "$LINES"
NUM=`echo "$LINES" | awk '{print $2}'`
[ -n "$NUM" ] && kill -9 $NUM
[ -n "$NUM" ] && echo "killed process $NUM"

exit 0
