#!/bin/bash

echo "running 'reset'"

rm -rf bitdust
git clone http://gitlab.bitdust.io/devel/bitdust.devel.git
mv bitdust.devel bitdust
cd bitdust
git config --global user.email "bitdust.io@gmail.com"
git config --global user.name "BitDust Node VPS"
git status
cd ..
