#!/bin/bash

IFS=$'\n' read -d '' -r -a nodes < nodes.txt
echo "target nodes:"
echo "${nodes[@]}"

for node in ${nodes[@]}
do
  echo ""
  echo "----------------------------------------------------"
  echo "[$node]"
  echo "scp scripts to $node ..."
  scp -q bd cmd go run loop stop up see kill "$node:"
  echo "chmod +x on scripts"
  ssh $node "chmod +x ./bd ./cmd ./go ./run ./loop ./stop ./up ./see ./kill"
  ssh $node "chmod +x ./cmd; ./cmd $node"
  echo "clean up all scripts"
  ssh $node "rm ./bd ./cmd ./go ./run ./loop ./stop ./up ./see ./kill"
done
