#!/bin/bash

for n in "00" "01" "02" "03" "04" "05" "06" "07" "08" "09" "10" "11" "12" "13" "14" "15"
do
  name="vps10$n"
  echo ++++++++++++++++++ $name +++++++++++++++++++++
  scp -q bd cmd go run loop stop up reset reset.devel see install idcreate grepnkill "$name:"
  scp cmd "$name:"
  ssh $name "chmod +x ./cmd; ./cmd $name"
done
