#!/bin/bash

IFS=$'\n' read -d '' -r -a nodes < nodes.txt
echo "target nodes:"
echo "${nodes[@]}"
echo "----------------------------------------------------"
for node in ${nodes[@]}
do
  echo "[$node]"
  ssh $node "cd bitdust; python bitdust.py idurl; python bitdust.py automats list | grep -e p2p_connector -e BitDust"
done