; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define   Name       "Miramishi Painter"
#define   Version    "0.0.1"
#define   Publisher  "Miramishi"
#define   URL        "http://www.bitdust.io"
#define   ExeName    ".exe"

[Setup]

