#!/bin/bash

set -e

cd ~/bitpie/release/ubuntu_devel

version=`cat ../version`
dirname="bitpie-$version.orig"
packagename="bitpie_${version}_all.deb"

echo "remove old files"
rm -f bitpie*.deb 
rm -f bitpie*.changes 
rm -f bitpie*.dsc 
rm -f bitpie*.gz 
rm -f bitpie*.upload
rm -f bitpie*.build

echo "prepare workspace folders"
rm -rf workspace
mkdir workspace
cd workspace
mkdir src
mkdir bin
mkdir doc
mkdir pixmaps
mkdir shortcuts
mkdir autostart
mkdir apt
mkdir cron
mkdir cron/daily
mkdir cron/hourly
mkdir debian
mkdir debian/source
mkdir default
cd ..

echo "prepare debian files"
echo "3.0 (native)" > workspace/debian/source/format
cp debian/compat workspace/debian/
cp debian/control workspace/debian/
cp debian/rules workspace/debian/
cp debian/install workspace/debian/
python -c "import sys;src=open(sys.argv[1]).read();src=src.replace('{version}',sys.argv[2]);open(sys.argv[1],'w').write(src);" workspace/debian/control $version
cp debian/changelog workspace/debian/
python -c "import sys,time;src=open(sys.argv[1]).read();src=src.replace('{version}',sys.argv[2]);src=src.replace('{date}',time.strftime('%a, %d %b %Y %H:%M:%S')); chlg=open('../../CHANGELOG.txt').read(); chlg=chlg[chlg.rfind('Veselin Penev <veselin@bitpie.net>')-12:]; src=src.replace('{changelog}',chlg); open(sys.argv[1],'w').write(src);" workspace/debian/changelog $version
cp debian/preinst workspace/debian
cp debian/postinst workspace/debian
cp debian/prerm workspace/debian
cp debian/copyright workspace/debian
# cp debian/bitpie.cron.daily workspace/debian 
cp debian/bitpie.cron.hourly workspace/debian 
cp debian/bitpie.menu workspace/shortcuts 

echo "prepare project files"
cp debian/bitpie.1 workspace/doc
cp debian/bitpie workspace/bin
cp debian/bitpie.xpm workspace/pixmaps
cp debian/bitpie.png workspace/pixmaps
cp debian/bitpie.list workspace/apt 
cp debian/bitpie.desktop workspace/shortcuts
cp -T debian/bitpie-autostart.desktop workspace/autostart/bitpie.desktop
cp -T debian/bitpie.default workspace/default/bitpie-update 

echo "build sources"
../sources/0-build

echo "copy sources"
cp -r ../sources/workspace/bitpie/* workspace/src/

# echo "rename LICENSE.txt file"
# mv workspace/src/LICENSE.txt workspace/src/TERMS.txt

echo "create repo.txt file"
echo "devel" > workspace/src/repo.txt
echo "http://bitpie.net/deb/devel" >> workspace/src/repo.txt

echo "setting permissions"
find workspace/debian -type d | xargs chmod 0755
find workspace/debian -type f | xargs chmod 0644
chmod 0755 workspace/bin/bitpie
chmod 0755 workspace/debian/rules
chmod 0755 workspace/debian/postinst
chmod 0755 workspace/debian/preinst
chmod 0755 workspace/debian/prerm
chmod 0755 workspace/debian/bitpie.cron.hourly
# chmod 0755 workspace/debian/bitpie.cron.daily

echo "DONE!"

exit 0

