#!/bin/sh

set -e

cd ~/bitdust/release/ubuntu_devel

version=`cat ../version`
debfile="bitdust_${version}_all.deb"
changesfile="bitdust_${version}_amd64.changes"

echo "copy .deb file into public location"
rm -f /var/www/bitdust-ubuntu-devel.deb
cp $debfile /var/www/download/bitdust-ubuntu-devel.deb

echo "doing reprepro"
reprepro -V -b /var/www/deb/devel include devel $changesfile
reprepro -V -b /var/www/deb/devel includedeb devel $debfile
reprepro -V -b /var/www/deb/devel list devel

rm -f bitdust_*

echo "DONE!!! apt repo updated!"

exit 0

