#!/bin/sh

set -e

cd ~/bitpie/release/ubuntu_devel

version=`cat ../version`
debfile="bitpie_${version}_all.deb"
changesfile="bitpie_${version}_amd64.changes"

echo "copy .deb file into public location"
rm -f /var/www/bitpie-ubuntu-devel.deb
cp $debfile /var/www/download/bitpie-ubuntu-devel.deb

echo "doing reprepro"
reprepro -V -b /var/www/deb/devel include devel $changesfile
reprepro -V -b /var/www/deb/devel includedeb devel $debfile
reprepro -V -b /var/www/deb/devel list devel

rm -f bitpie_*

echo "DONE!!! apt repo updated!"

exit 0

