FROM bitdust_perf/base

ENV DHT_SEED_1='dht_seed_1:14441'
ENV DHT_SEED_2='dht_seed_2:14441'
ENV PYTHONPATH=/bitdust

#ENTRYPOINT /root/.bitdust/venv/bin/python tests/perf/test_producer.py
ENTRYPOINT sleep infinity
